version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: saga-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: saga_orchestrator
    volumes:
      - mongodb_data:/data/db
    networks:
      - saga-network

  saga-orchestrator:
    build: .
    container_name: saga-orchestrator
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/saga_orchestrator
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - saga-network

volumes:
  mongodb_data:

networks:
  saga-network:
    driver: bridge 