spring:
  application:
    name: saga-orchestrator
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/saga_orchestrator}
      database: saga_orchestrator
      auto-index-creation: true
  
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=300s  # Increased cache size for higher throughput

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,sagas
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    sagas:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.saga: INFO
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/saga-orchestrator.log
    max-size: 100MB
    max-history: 30

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

saga:
  execution:
    max-retries: 3
    retry-delay-ms: 1000
    timeout-ms: 30000
    thread-pool:
      core-size: 50             # Increased for higher throughput
      max-size: 200             # Increased max threads
      queue-capacity: 2000      # Increased queue capacity
      keep-alive-seconds: 60
  
  mongodb:
    connection-pool:
      max-size: 200             # Increased for higher concurrency
      min-size: 20              # Increased minimum connections
      max-wait-time: 30000
      max-connection-life-time: 300000
      max-connection-idle-time: 60000
  
  rate-limit:
    requests-per-minute: 1200   # Increased to handle 1000 + buffer
    requests-per-hour: 60000    # Increased hourly limit
    burst-size: 200             # Increased burst capacity
  
  circuit-breaker:
    failure-threshold: 5
    timeout-seconds: 30
    success-threshold: 3
  
  compensation:
    enabled: true
    timeout-ms: 15000
  
  monitoring:
    enabled: true
    metrics-enabled: true
    health-check-enabled: true
    performance-tracking-enabled: true 